### ISSUE TITLE
add a `close()` method for `PlotArea`

### ISSUE THREAD

**Issue by kushalkolar** [kushalkolar/fastplotlib#119]
Currently if a user wants to close a plot they need to access the canvas, `plot.canvas.close()`, to reduce boilerplate we can implement `plot.close()`.

@EricThomson, @clewis7 thoughts?

**Comment by kushalkolar** [comment]
@EricThomson also let me know of any other boilerplate you notice that you think can be removed.

**Comment by clewis7** [comment]
I think plot.close()

**Comment by EricThomson** [comment]
Sounds like a good idea. What about with widgets, too, so `widget.close()`? Seems like this could be made a natural/expected part of the api.  Basically, if you can show it, you can close it.

**Comment by kushalkolar** [comment]
Yes like for `ImageWidget`, it can close all the sliders, VBox, and plot.

@EricThomson is this your first contrib? :D

**Comment by EricThomson** [comment]
This is great, I obsessively like to close things. :)
