### ISSUE TITLE
Open multiseries tiff file with LazyArrays

### ISSUE THREAD

**Issue by RuiOSilva** [kushalkolar/fastplotlib#128]
I cannot open multiseries tiff files with Lazy Arrays. I have some multiseries recordings and also that is also how I convert .mmap files into .tiff files again when the files are bigger than my RAM or when I want to decrease the floating precision of the data for longer storage. It would be great if this was possible for fast visualizations.

**Comment by kushalkolar** [comment]
LazyArrays are a mesmerize thing, you can now manually set the shape if you use the latest version on the repo. You could also subclass it with parsing logic for your file format. If you have further issues you can post it there.
