### ISSUE TITLE
[Windows 8] create_instance: ERROR_INCOMPATIBLE_DRIVER

### ISSUE THREAD

**Issue by njm94** [kushalkolar/fastplotlib#134]
Hi, I am trying to get the [mescore ](https://github.com/EricThomson/CCN_caiman_mesmerize_workshop_2023)environment running with caiman, fastplotlib and mesmerize-core.

OS: windows 8, x86
env: mamba with caiman, mesmerize-core, fastplotlib

I was able to install all the packages in the environment as mentioned but while running the demo code simple.ipynb, the following fastplotlib command throws an error
`# create a Plot instance`
`plot = Plot()`

I am pasting the error output below-
Thanks for your help!

> ---------------------------------------------------------------------------
> AssertionError                            Traceback (most recent call last)
> Cell In[2], line 2
>       1 # create a `Plot` instance
> ----> 2 plot = Plot()
>       4 # make some random 2D image data
>       5 data = np.random.rand(512, 512)
> 
> File C:\ProgramData\miniforge3\envs\mescore\lib\site-packages\fastplotlib\plot.py:76, in Plot.__init__(self, canvas, renderer, camera, controller, **kwargs)
>       8 def __init__(
>       9         self,
>      10         canvas: WgpuCanvas = None,
>    (...)
>      14         **kwargs
>      15 ):
>      16     """
>      17     Simple Plot object.
>      18 
>    (...)
>      74 
>      75     """
> ---> 76     super(Plot, self).__init__(
>      77         position=(0, 0),
>      78         parent_dims=(1, 1),
>      79         canvas=canvas,
>      80         renderer=renderer,
>      81         camera=camera,
>      82         controller=controller,
>      83         **kwargs
>      84     )
> 
> File C:\ProgramData\miniforge3\envs\mescore\lib\site-packages\fastplotlib\layouts\_subplot.py:34, in Subplot.__init__(self, position, parent_dims, camera, controller, canvas, renderer, name, **kwargs)
>      31     canvas = WgpuCanvas()
>      33 if renderer is None:
> ---> 34     renderer = WgpuRenderer(canvas)
>      36 if position is None:
>      37     position = (0, 0)
> 
> File C:\ProgramData\miniforge3\envs\mescore\lib\site-packages\pygfx\renderers\wgpu\_renderer.py:151, in WgpuRenderer.__init__(self, target, pixel_ratio, show_fps, blend_mode, sort_objects, enable_events, gamma_correction, *args, **kwargs)
>     149 canvas = target if isinstance(target, wgpu.gui.WgpuCanvasBase) else None
>     150 if Shared._instance is None:  # == self._shared
> --> 151     Shared(canvas)
>     153 # Init counter to auto-clear
>     154 self._renders_since_last_flush = 0
> 
> File C:\ProgramData\miniforge3\envs\mescore\lib\site-packages\pygfx\renderers\wgpu\_shared.py:50, in Shared.__init__(self, canvas)
>      41 Shared._instance = self
>      43 # Create adapter and device objects - there should be just one per canvas.
>      44 # Having a global device provides the benefit that we can draw any object
>      45 # anywhere.
>    (...)
>      48 # However, passing the object has been shown to prevent the creation of
>      49 # a canvas (on Linux + wx), so, we never pass it for now.
> ---> 50 self._adapter = wgpu.request_adapter(
>      51     canvas=None, power_preference="high-performance"
>      52 )
>      53 self._device = self.adapter.request_device(
>      54     required_features=[], required_limits={}
>      55 )
>      57 # Create a uniform buffer for std info
>      58 # Stored on _store so if we'd ever swap it out for another buffer,
>      59 # the pipeline automatically update.
> 
> File C:\ProgramData\miniforge3\envs\mescore\lib\site-packages\wgpu\backends\rs.py:282, in GPU.request_adapter(self, canvas, power_preference)
>     278 lib.wgpuInstanceRequestAdapter(get_wgpu_instance(), struct, callback, ffi.NULL)
>     280 # For now, Rust will call the callback immediately
>     281 # todo: when wgpu gets an event loop -> while run wgpu event loop or something
> --> 282 assert adapter_id is not None
>     284 # ----- Get adapter info
>     285 
>     286 # H: nextInChain: WGPUChainedStructOut *, vendorID: int, vendorName: char *, architecture: char *, deviceID: int, name: char *, driverDescription: char *, adapterType: WGPUAdapterType, backendType: WGPUBackendType
>     287 c_properties = new_struct_p(
>     288     "WGPUAdapterProperties *",
>     289     # not used: nextInChain
>    (...)
>     297     # not used: architecture
>     298 )
> 
> AssertionError:

**Comment by kushalkolar** [comment]
Windows 8 doesn't come with Vulkan drivers as far as I know, but I think win10 and win11 come with it. I don't know how to install vulkan drivers on Windows 8.
