### ISSUE TITLE
chaining `link()`

### ISSUE THREAD

**Issue by kushalkolar** [kushalkolar/fastplotlib#136]
maybe allow this type of usage?

```python
img_graphic.link("click", target=contours_graphics, feature="colors", new_data="w", callback=euclidean)
    .link("colors", target=contours_graphic, feature="thickness", new_data=4)
    .link("colors", target=temporal_graphic, feature="present", new_data=True)
```

this would mean `Graphic.link()` has to return the target `Graphic` instance.

@clewis7 thoughts?

**Comment by clewis7** [comment]
I think it would be fine, would reduce having to have three separate calls but you still could if you wanted to

**Comment by kushalkolar** [comment]
what about also allowing:
- `target` to be a list of `Graphic` instances
- `feature` to be a list of valid feature strings, and then `new_data` should be a mapping of `{feature: new_data}` ?

I think it gets messy but I'm trying to figure out a nice API to make lots of linkages more elegant, what about:

```python
img_graphic.link.click(euclidean) >> contours_graphics.link.colors("w") >> contours_graphic.link.thickness(3.0) >> temporal_graphic.link.present(True)
```

I think this is possible by just using `__rshift__()`, just trying to come up with API now :thinking:

**Comment by clewis7** [comment]
I think that is cleaner than .link over and over again

**Comment by kushalkolar** [comment]
I think this is messy, and we have bidirectional now. Closing, can revisit if we see the need.
