### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by clewis7** [kushalkolar/fastplotlib#152]
- [ ] Graphics
    - [x] `Image`
        - [x] 2D 512x512 rand image which is pre-saved with cmaps
            - [x] changing cmap
        - [x] 2D RGB array, imageio example images
        - [x] changing vmin vmax
    - [x] `Line`
      - [x] sine, cosine, sinc from examples
          - [x] slicing colors, data
          - [x] present followed by auto_scale()
    - [x] `Scatter`
    - [x] `GridPlot`
    - [x] `ImageWidget`
    - [x] upload screenshot test images and diffs if tests failed: see https://github.com/pygfx/pygfx/blob/main/.github/workflows/ci.yml#L132 and https://github.com/actions/upload-artifact

**Comment by kushalkolar** [comment]
You can basically go through our demos and edit the list here to add the remaining list of tests
