### ISSUE TITLE
Accepted nested tuples as input for camera/controller

### ISSUE THREAD

**Issue by ArjunPutcha** [kushalkolar/fastplotlib#17]
Shape tuple is already set, should have handler to accept both array and tuples as valid input for camera and controller params

**Comment by kushalkolar** [comment]
@ArjunPutcha Want to try and implement?

**Comment by ArjunPutcha** [comment]
Of course @kushalkolar ! Go rest

**Comment by kushalkolar** [comment]
done in #45
