### ISSUE TITLE
Demo Notebook Error

### ISSUE THREAD

**Issue by ambtetl** [kushalkolar/fastplotlib#184]
I have installed mesmerize-core on an M1 Mac. I followed the instructions for the install but swapped out miniconda for anaconda, please let me know if this created my issue. I did this because mamba would not install. When I followed the remaining instructions I did not receive any error messages. However, when accessing the fastplotlib demo notebook as in the youtube video, I receive the following error in the second cells of code.  

Simple image
# create a `Plot` instance
plot = Plot()
​
# make some random 2D image data
data = np.random.rand(512, 512)
​
# plot the image data
image_graphic = plot.add_image(data=data, name="random-image")
​
# show the plot
plot.show()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 2
      1 # create a `Plot` instance
----> 2 plot = Plot()
      4 # make some random 2D image data
      5 data = np.random.rand(512, 512)

File ~/miniconda3/envs/mescore/lib/python3.10/site-packages/fastplotlib/plot.py:76, in Plot.__init__(self, canvas, renderer, camera, controller, **kwargs)
      8 def __init__(
      9         self,
     10         canvas: WgpuCanvas = None,
   (...)
     14         **kwargs
     15 ):
     16     """
     17     Simple Plot object.
     18 
   (...)
     74 
     75     """
---> 76     super(Plot, self).__init__(
     77         position=(0, 0),
     78         parent_dims=(1, 1),
     79         canvas=canvas,
     80         renderer=renderer,
     81         camera=camera,
     82         controller=controller,
     83         **kwargs
     84     )

File ~/miniconda3/envs/mescore/lib/python3.10/site-packages/fastplotlib/layouts/_subplot.py:85, in Subplot.__init__(self, position, parent_dims, camera, controller, canvas, renderer, name, **kwargs)
     82 self._animate_funcs_pre = list()
     83 self._animate_funcs_post = list()
---> 85 super(Subplot, self).__init__(
     86     parent=None,
     87     position=position,
     88     camera=create_camera(camera),
     89     controller=controller,
     90     scene=Scene(),
     91     canvas=canvas,
     92     renderer=renderer,
     93     name=name
     94 )
     96 for pos in ["left", "top", "right", "bottom"]:
     97     dv = _DockedViewport(self, pos, size=0)

File ~/miniconda3/envs/mescore/lib/python3.10/site-packages/fastplotlib/layouts/_base.py:73, in PlotArea.__init__(self, parent, position, camera, controller, scene, canvas, renderer, name)
     70 self._camera = camera
     71 self._controller = controller
---> 73 self.controller.add_camera(self.camera)
     74 self.controller.register_events(
     75     self.viewport,
     76 )
     78 self.renderer.add_event_handler(self.set_viewport_rect, "resize")

AttributeError: 'PanZoomController' object has no attribute 'add_camera'

**Comment by kushalkolar** [comment]
It looks like you installed fastplotlib directly from GitHub? The master
branch on GitHub tracks the latest upstream changes to pygfx (the rendering
engine that fastplotlib uses), and both pygfx and fastplotlib are in rapid
development so things change frequently. You have two options:
1. If you want to use the latest fastplotlib from GitHub you should use the
latest pygfx from GitHub as well.
2. Install fastplotlib from pypi instead of GitHub, i.e. `pip install -U
fastplotlib`. This is what I'd recommend if you're not too familiar with
Python.

**Comment by ambtetl** [comment]
Thank you! The pip install worked for me.
