### ISSUE TITLE
Failed to load model class 'RemoteFrameBufferModel'

### ISSUE THREAD

**Issue by EricThomson** [kushalkolar/fastplotlib#185]
Running simple demos, nothing is rendering I keep hitting the same error:

`Failed to load model class 'RemoteFrameBufferModel' from module 'jupyter_rfb'`

I just did a fresh install of caiman. I have jupyter-rfb 0.4.1, fastplotlib 0.1.0a9, simplejpeg 1.6.6. I'm sure there are other dependencies you would need to know about, but those are the main ones.

**Comment by kushalkolar** [comment]
jupyter_rfb just updated to v0.4.1 which requires Python 3.9. Are you on
3.9 or higher?

If not you can use jupyter_rfb<0.4.0

**Comment by EricThomson** [comment]
I'm in Python 3.10.  Here's the output of `conda list`:

> _tflow_select             2.3.0                       mkl
> absl-py                   1.4.0              pyhd8ed1ab_0    conda-forge
> aiofiles                  22.1.0                   pypi_0    pypi
> aiohttp                   3.7.4.post0     py310he2412df_1    conda-forge
> aiosqlite                 0.19.0                   pypi_0    pypi
> anyio                     3.6.2              pyhd8ed1ab_0    conda-forge
> aom                       3.5.0                h63175ca_0    conda-forge
> argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
> argon2-cffi-bindings      21.2.0          py310h8d17308_3    conda-forge
> arrow                     1.2.3                    pypi_0    pypi
> asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
> astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
> async-timeout             3.0.1                   py_1000    conda-forge
> attrs                     22.2.0             pyh71513ae_0    conda-forge
> babel                     2.12.1                   pypi_0    pypi
> backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
> backports                 1.0                pyhd8ed1ab_3    conda-forge
> backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
> beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
> bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
> blinker                   1.6.2              pyhd8ed1ab_0    conda-forge
> blosc                     1.21.3               hdccc3a2_0    conda-forge
> bokeh                     2.4.3              pyhd8ed1ab_3    conda-forge
> brotli                    1.0.9                hcfcfb64_8    conda-forge
> brotli-bin                1.0.9                hcfcfb64_8    conda-forge
> brotlipy                  0.7.0           py310h8d17308_1005    conda-forge
> bzip2                     1.0.8                h8ffe710_4    conda-forge
> c-ares                    1.18.1               h8ffe710_0    conda-forge
> c-blosc2                  2.8.0                h183a6f4_1    conda-forge
> ca-certificates           2022.12.7            h5b45459_0    conda-forge
> cached-property           1.5.2                hd8ed1ab_1    conda-forge
> cached_property           1.5.2              pyha770c72_1    conda-forge
> cachetools                5.3.0              pyhd8ed1ab_0    conda-forge
> caiman                    1.9.15          py310h1c4a608_0    conda-forge
> certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
> cffi                      1.15.1          py310h628cb3f_3    conda-forge
> cfitsio                   4.2.0                h9ebe7e4_0    conda-forge
> chardet                   4.0.0           py310h5588dad_3    conda-forge
> charls                    2.4.1                h1537add_0    conda-forge
> charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
> click                     8.1.3           win_pyhd8ed1ab_2    conda-forge
> cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
> colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
> colorcet                  3.0.1              pyhd8ed1ab_0    conda-forge
> comm                      0.1.3              pyhd8ed1ab_0    conda-forge
> contourpy                 1.0.7           py310h232114e_0    conda-forge
> cryptography              39.0.0          py310h52f42fa_0    conda-forge
> cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
> cytoolz                   0.12.0          py310h8d17308_1    conda-forge
> dask-core                 2023.4.1           pyhd8ed1ab_0    conda-forge
> dav1d                     1.0.0                h8ffe710_1    conda-forge
> debugpy                   1.6.7           py310h00ffb61_0    conda-forge
> decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
> defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
> eigen                     3.4.0                h2d74725_0    conda-forge
> entrypoints               0.4                pyhd8ed1ab_0    conda-forge
> executing                 1.2.0              pyhd8ed1ab_0    conda-forge
> fastplotlib               0.1.0a9                  pypi_0    pypi
> flatbuffers               23.3.3               h63175ca_0    conda-forge
> flit-core                 3.8.0              pyhd8ed1ab_0    conda-forge
> fonttools                 4.39.3          py310h8d17308_0    conda-forge
> fqdn                      1.5.1                    pypi_0    pypi
> freetype                  2.12.1               h546665d_1    conda-forge
> freetype-py               2.3.0                    pypi_0    pypi
> fsspec                    2023.4.0           pyh1a96a4e_0    conda-forge
> future                    0.18.3             pyhd8ed1ab_0    conda-forge
> gast                      0.4.0              pyh9f0ad1d_0    conda-forge
> gettext                   0.21.1               h5728263_0    conda-forge
> giflib                    5.2.1                h64bf75a_3    conda-forge
> glib                      2.76.2               h12be248_0    conda-forge
> glib-tools                2.76.2               h12be248_0    conda-forge
> google-auth               2.17.3             pyh1a96a4e_0    conda-forge
> google-auth-oauthlib      0.4.6              pyhd8ed1ab_0    conda-forge
> google-pasta              0.2.0              pyh8c360ce_0    conda-forge
> grpc-cpp                  1.48.1               hcb02dd0_1    conda-forge
> grpcio                    1.48.1          py310h1177ea7_1    conda-forge
> gst-plugins-base          1.18.5               he07aa86_3    conda-forge
> gstreamer                 1.18.5               hdff456e_3    conda-forge
> h5py                      3.8.0           nompi_py310h727aef9_101    conda-forge
> hdf5                      1.14.0          nompi_h97a5375_103    conda-forge
> hdmf                      1.5.4                      py_0    conda-forge
> holoviews                 1.15.2             pyhd8ed1ab_0    conda-forge
> icu                       58.2                 ha925a31_3
> idna                      3.4                pyhd8ed1ab_0    conda-forge
> imagecodecs               2023.1.23       py310h35c0596_0    conda-forge
> imageio                   2.28.0             pyh24c5eb1_0    conda-forge
> importlib-metadata        6.6.0              pyha770c72_0    conda-forge
> importlib_metadata        6.6.0                hd8ed1ab_0    conda-forge
> importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
> intel-openmp              2023.1.0         h57928b3_46319    conda-forge
> ipykernel                 6.22.0             pyh025b116_0    conda-forge
> ipyparallel               8.6.1              pyhd8ed1ab_0    conda-forge
> ipython                   8.13.1             pyh08f2357_0    conda-forge
> ipython_genutils          0.2.0                      py_1    conda-forge
> ipywidgets                8.0.6              pyhd8ed1ab_0    conda-forge
> isoduration               20.11.0                  pypi_0    pypi
> jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
> jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
> joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
> jpeg                      9e                   hcfcfb64_3    conda-forge
> json5                     0.9.11                   pypi_0    pypi
> jsonpointer               2.3                      pypi_0    pypi
> jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
> jupyter                   1.0.0           py310h5588dad_8    conda-forge
> jupyter-rfb               0.4.1                    pypi_0    pypi
> jupyter-server-fileid     0.9.0                    pypi_0    pypi
> jupyter-server-ydoc       0.8.0                    pypi_0    pypi
> jupyter-ydoc              0.2.4                    pypi_0    pypi
> jupyter_client            8.2.0              pyhd8ed1ab_0    conda-forge
> jupyter_console           6.6.3              pyhd8ed1ab_0    conda-forge
> jupyter_core              5.3.0           py310h5588dad_0    conda-forge
> jupyter_events            0.6.3              pyhd8ed1ab_0    conda-forge
> jupyter_server            2.5.0              pyhd8ed1ab_0    conda-forge
> jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
> jupyterlab                3.6.3                    pypi_0    pypi
> jupyterlab-server         2.22.1                   pypi_0    pypi
> jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
> jupyterlab_widgets        3.0.7              pyhd8ed1ab_0    conda-forge
> jxrlib                    1.1                  h8ffe710_2    conda-forge
> keras                     2.10.0             pyhd8ed1ab_0    conda-forge
> kiwisolver                1.4.4           py310h232114e_1    conda-forge
> krb5                      1.20.1               h6609f42_0    conda-forge
> lazy_loader               0.2                pyhd8ed1ab_0    conda-forge
> lcms2                     2.15                 ha5c8aab_0    conda-forge
> lerc                      4.0.0                h63175ca_0    conda-forge
> libabseil                 20220623.0      cxx17_h1a56200_6    conda-forge
> libaec                    1.0.6                h63175ca_1    conda-forge
> libavif                   0.11.1               h8f5c5bc_0    conda-forge
> libblas                   3.9.0              16_win64_mkl    conda-forge
> libbrotlicommon           1.0.9                hcfcfb64_8    conda-forge
> libbrotlidec              1.0.9                hcfcfb64_8    conda-forge
> libbrotlienc              1.0.9                hcfcfb64_8    conda-forge
> libcblas                  3.9.0              16_win64_mkl    conda-forge
> libclang                  12.0.1          default_h81446c8_4    conda-forge
> libcurl                   7.88.1               h68f0423_1    conda-forge
> libdeflate                1.17                 hcfcfb64_0    conda-forge
> libffi                    3.4.2                h8ffe710_5    conda-forge
> libglib                   2.76.2               he8f3873_0    conda-forge
> libhwloc                  2.9.1                h51c2c0f_0    conda-forge
> libiconv                  1.17                 h8ffe710_0    conda-forge
> liblapack                 3.9.0              16_win64_mkl    conda-forge
> libogg                    1.3.4                h8ffe710_1    conda-forge
> libpng                    1.6.39               h19919ed_0    conda-forge
> libprotobuf               3.20.3               h12be248_0    conda-forge
> libsodium                 1.0.18               h8d14728_1    conda-forge
> libsqlite                 3.40.0               hcfcfb64_1    conda-forge
> libssh2                   1.10.0               h680486a_3    conda-forge
> libtiff                   4.5.0                hf8721a0_2    conda-forge
> libvorbis                 1.3.7                h0e60522_0    conda-forge
> libwebp                   1.3.0                hcfcfb64_0    conda-forge
> libwebp-base              1.3.0                hcfcfb64_0    conda-forge
> libxcb                    1.13              hcd874cb_1004    conda-forge
> libxml2                   2.10.4               hc3477c8_0    conda-forge
> libxslt                   1.1.37               h0192164_0    conda-forge
> libzlib                   1.2.13               hcfcfb64_4    conda-forge
> libzopfli                 1.0.3                h0e60522_0    conda-forge
> locket                    1.0.0              pyhd8ed1ab_0    conda-forge
> lz4-c                     1.9.4                hcfcfb64_0    conda-forge
> m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
> m2w64-gcc-libs            5.3.0                         7    conda-forge
> m2w64-gcc-libs-core       5.3.0                         7    conda-forge
> m2w64-gmp                 6.1.0                         2    conda-forge
> m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
> markdown                  3.4.3              pyhd8ed1ab_0    conda-forge
> markupsafe                2.1.2           py310h8d17308_0    conda-forge
> matplotlib                3.7.1           py310h5588dad_0    conda-forge
> matplotlib-base           3.7.1           py310h51140c5_0    conda-forge
> matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
> mistune                   2.0.5              pyhd8ed1ab_0    conda-forge
> mkl                       2022.1.0           h6a75c08_874    conda-forge
> msys2-conda-epoch         20160418                      1    conda-forge
> multidict                 6.0.4           py310h8d17308_0    conda-forge
> munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
> mypy                      1.2.0           py310h8d17308_0    conda-forge
> mypy_extensions           1.0.0              pyha770c72_0    conda-forge
> nbclassic                 0.5.6              pyhb4ecaf3_1    conda-forge
> nbclient                  0.7.4              pyhd8ed1ab_0    conda-forge
> nbconvert                 7.3.1              pyhd8ed1ab_0    conda-forge
> nbconvert-core            7.3.1              pyhd8ed1ab_0    conda-forge
> nbconvert-pandoc          7.3.1              pyhd8ed1ab_0    conda-forge
> nbformat                  5.8.0              pyhd8ed1ab_0    conda-forge
> nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
> networkx                  3.1                pyhd8ed1ab_0    conda-forge
> nose                      1.3.7                   py_1006    conda-forge
> notebook                  6.5.4              pyha770c72_0    conda-forge
> notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
> numpy                     1.24.3          py310hd02465a_0    conda-forge
> oauthlib                  3.2.2              pyhd8ed1ab_0    conda-forge
> opencv                    4.6.0           py310ha7641e4_2
> openjpeg                  2.5.0                ha2aaf27_2    conda-forge
> openssl                   1.1.1t               hcfcfb64_0    conda-forge
> opt_einsum                3.3.0              pyhd8ed1ab_1    conda-forge
> packaging                 23.1               pyhd8ed1ab_0    conda-forge
> pandas                    2.0.1           py310h1c4a608_0    conda-forge
> pandoc                    2.19.2               h57928b3_2    conda-forge
> pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
> panel                     0.14.4             pyhd8ed1ab_0    conda-forge
> param                     1.13.0             pyh1a96a4e_0    conda-forge
> parso                     0.8.3              pyhd8ed1ab_0    conda-forge
> partd                     1.4.0              pyhd8ed1ab_0    conda-forge
> pcre2                     10.40                h17e33f8_0    conda-forge
> peakutils                 1.3.4              pyhd8ed1ab_0    conda-forge
> pickleshare               0.7.5                   py_1003    conda-forge
> pillow                    9.4.0           py310hdbb7713_1    conda-forge
> pims                      0.6.1              pyhd8ed1ab_0    conda-forge
> pip                       23.1.2             pyhd8ed1ab_0    conda-forge
> pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
> platformdirs              3.5.0              pyhd8ed1ab_0    conda-forge
> pooch                     1.7.0              pyha770c72_3    conda-forge
> prometheus_client         0.16.0             pyhd8ed1ab_0    conda-forge
> prompt-toolkit            3.0.38             pyha770c72_0    conda-forge
> prompt_toolkit            3.0.38               hd8ed1ab_0    conda-forge
> protobuf                  3.20.3          py310h5588dad_1    conda-forge
> psutil                    5.9.5           py310h8d17308_0    conda-forge
> pthread-stubs             0.4               hcd874cb_1001    conda-forge
> pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
> pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
> pyasn1                    0.4.8                      py_0    conda-forge
> pyasn1-modules            0.2.7                      py_0    conda-forge
> pycparser                 2.21               pyhd8ed1ab_0    conda-forge
> pyct                      0.4.6                      py_0    conda-forge
> pyct-core                 0.4.6                      py_0    conda-forge
> pygfx                     0.1.12                   pypi_0    pypi
> pygments                  2.15.1             pyhd8ed1ab_0    conda-forge
> pyjwt                     2.6.0              pyhd8ed1ab_0    conda-forge
> pynwb                     1.2.1                      py_0    conda-forge
> pyopenssl                 23.1.1             pyhd8ed1ab_0    conda-forge
> pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
> pyqt                      5.15.4          py310h8a704f9_0    conda-forge
> pyqt5-sip                 12.9.0          py310h8a704f9_0    conda-forge
> pyqtgraph                 0.13.3             pyhd8ed1ab_0    conda-forge
> pyrsistent                0.19.3          py310h8d17308_0    conda-forge
> pysocks                   1.7.1              pyh0701188_6    conda-forge
> python                    3.10.8          h0269646_0_cpython    conda-forge
> python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
> python-fastjsonschema     2.16.3             pyhd8ed1ab_0    conda-forge
> python-flatbuffers        23.1.21            pyhd8ed1ab_0    conda-forge
> python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
> python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
> python_abi                3.10                    3_cp310    conda-forge
> pytz                      2023.3             pyhd8ed1ab_0    conda-forge
> pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
> pyviz_comms               2.2.1              pyhd8ed1ab_1    conda-forge
> pywavelets                1.4.1           py310h9b08ddd_0    conda-forge
> pywin32                   304             py310h00ffb61_2    conda-forge
> pywinpty                  2.0.10          py310h00ffb61_0    conda-forge
> pyyaml                    6.0             py310h8d17308_5    conda-forge
> pyzmq                     25.0.2          py310hcd737a0_0    conda-forge
> qt-main                   5.15.2               he8e5bd7_7
> qt-webengine              5.15.9               hb9a9bb5_5
> qtconsole                 5.4.2              pyhd8ed1ab_0    conda-forge
> qtconsole-base            5.4.2              pyha770c72_0    conda-forge
> qtpy                      2.3.1              pyhd8ed1ab_0    conda-forge
> qtwebkit                  5.212                h2bbfb41_5
> re2                       2022.06.01           h0e60522_1    conda-forge
> requests                  2.29.0             pyhd8ed1ab_0    conda-forge
> requests-oauthlib         1.3.1              pyhd8ed1ab_0    conda-forge
> rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
> rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
> rsa                       4.9                pyhd8ed1ab_0    conda-forge
> ruamel.yaml               0.17.21         py310h8d17308_3    conda-forge
> ruamel.yaml.clib          0.2.7           py310h8d17308_1    conda-forge
> scikit-image              0.20.0          py310h1c4a608_1    conda-forge
> scikit-learn              1.2.2           py310hd266714_1    conda-forge
> scipy                     1.10.1          py310h578b7cb_0    conda-forge
> send2trash                1.8.2              pyh08f2357_0    conda-forge
> setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
> simplejpeg                1.6.6                    pypi_0    pypi
> sip                       6.5.1           py310h8a704f9_2    conda-forge
> six                       1.16.0             pyh6c4a22f_0    conda-forge
> slicerator                1.1.0              pyhd8ed1ab_0    conda-forge
> snappy                    1.1.10               hfb803bf_0    conda-forge
> sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
> soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
> sqlite                    3.41.2               h2bbff1b_0
> stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
> tbb                       2021.9.0             h91493d7_0    conda-forge
> tensorboard               2.10.1             pyhd8ed1ab_0    conda-forge
> tensorboard-data-server   0.6.1           py310h5588dad_4    conda-forge
> tensorboard-plugin-wit    1.8.1              pyhd8ed1ab_0    conda-forge
> tensorflow                2.10.0          mkl_py310hd99672f_0
> tensorflow-base           2.10.0          mkl_py310h6a7f48e_0
> tensorflow-estimator      2.10.0          py310haa95532_0
> termcolor                 2.3.0              pyhd8ed1ab_0    conda-forge
> terminado                 0.17.0             pyh08f2357_0    conda-forge
> threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
> tifffile                  2023.4.12          pyhd8ed1ab_0    conda-forge
> tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
> tk                        8.6.12               h8ffe710_0    conda-forge
> toml                      0.10.2             pyhd8ed1ab_0    conda-forge
> tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
> toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
> tornado                   6.3             py310h8d17308_0    conda-forge
> tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
> traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
> typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
> typing_extensions         4.5.0              pyha770c72_0    conda-forge
> tzdata                    2023c                h71feb2d_0    conda-forge
> ucrt                      10.0.22621.0         h57928b3_0    conda-forge
> uharfbuzz                 0.36.0                   pypi_0    pypi
> unicodedata2              15.0.0          py310h8d17308_0    conda-forge
> uri-template              1.2.0                    pypi_0    pypi
> urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
> vc                        14.3                h3d8a991_11    conda-forge
> vs2015_runtime            14.34.31931         h4c5c07a_11    conda-forge
> wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
> webcolors                 1.13                     pypi_0    pypi
> webencodings              0.5.1                      py_1    conda-forge
> websocket-client          1.5.1              pyhd8ed1ab_0    conda-forge
> werkzeug                  2.3.2              pyhd8ed1ab_0    conda-forge
> wgpu                      0.9.4                    pypi_0    pypi
> wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
> widgetsnbextension        4.0.7              pyhd8ed1ab_0    conda-forge
> win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
> winpty                    0.4.3                         4    conda-forge
> wrapt                     1.15.0          py310h8d17308_0    conda-forge
> xorg-libxau               1.0.9                hcd874cb_0    conda-forge
> xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
> xz                        5.2.6                h8d14728_0    conda-forge
> y-py                      0.5.9                    pypi_0    pypi
> yaml                      0.2.5                h8ffe710_2    conda-forge
> yarl                      1.9.1           py310h8d17308_0    conda-forge
> ypy-websocket             0.8.2                    pypi_0    pypi
> z5py                      2.0.16          py310h51f9496_0    conda-forge
> zeromq                    4.3.4                h0e60522_1    conda-forge
> zfp                       1.0.0                h63175ca_3    conda-forge
> zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
> zlib                      1.2.13               hcfcfb64_4    conda-forge
> zlib-ng                   2.0.7                hcfcfb64_0    conda-forge
> zstd                      1.5.2                h12be248_6    conda-forge

**Comment by kushalkolar** [comment]
Do ordinary ipywidgets work? Like IntSlider

**Comment by EricThomson** [comment]
I restarted all the things, and everything is working well now. Sorry for the false alarm!

**Comment by kushalkolar** [comment]
What do you mean restarted everything? If you install jupyter_rfb while
jupyterlab is running you do need to start a new jupyterlab to get any new
widget stuff you've since installed. This is true in general for anything
jupyter related, whereas most other Python libs you can install and it will
take effect if you just restart the kernel but don't restart jupyter.
