### ISSUE TITLE
Trying to plot line of different thread but I can't see the canvas

### ISSUE THREAD

**Issue by dnussinson** [kushalkolar/fastplotlib#196]
This is my code following your suggestion, I must be doing something stupid:

import numpy as np
import multiprocessing as mp
from multiprocessing import Process
import time
from fastplotlib import Plot
from fastplotlib import run as run_plot

class PlotProcess(Process):
    def __init__(self, qu):
        self.qu = qu
        self.xs = np.linspace(0, 9, 1000, dtype=np.float32)
        # Create a plot instance
        self.plot_l = Plot()
        data = np.zeros(1000,dtype=np.float32)
        data = np.dstack((self.xs, self.xs))[0]
        # plot sine wave, use a single color
        self.line_graphic = self.plot_l.add_line(data=data, thickness=5, colors="magenta")
        self.plot_l.show()
        self.plot_l.add_animations(self.update_plot)

    def update_plot(self, plot_instance):
        new_data = self.qu.get()
        plot_instance[0].data[:,1] = new_data

    # override the run function
    def run(self):
        run_plot()

def generate_ydata():
    return np.random.rand(1000, 2)

if __name__ == "__main__":
    q = mp.Queue()
    process = mp.Process(target=PlotProcess, args=(q,), daemon=True)
    q.put(generate_ydata())
    process.start()
    time.sleep(0.1)
    for i in range(50):
        q.put(generate_ydata())
        time.sleep(0.2)
        print(i)
    time.sleep(1)
    process.join()

**Comment by kushalkolar** [comment]
You'll need to run the visualization in local process, and generate and
generate the data in another process.

**Comment by kushalkolar** [comment]
I think what's really the easiest way to do this is with `zmq` rather than python multiprocessing, I have an example of a nb for the visualization side of things here: https://github.com/project-improv/improv/blob/338b40f8e0604da08cb8af54cf3b4d56668f5717/demos/fastplotlib/fastplotlib.ipynb

It's for image data but can be adapted. Depending on the specific of your data streaming you'll have to decide if you want to queue and keep messages (new data points) or only keep and plot the most recent ones. Because `zmq` can work at ~5,000Hz easily for 512x512 uint16 data, and that's MUCH faster than any monitor can display.

**Comment by dnussinson** [comment]
I got this to run using multiprocessing.Array. probably no as efficient as zmq. 
thanks agai
here is my code, if it helps someone:

import numpy as np
import multiprocessing as mp
from fastplotlib import Plot
from fastplotlib import run as run_plot
import ctypes


def generate_ydata(shared_arr,event):
    while True:
        #print('Hi I am in callback!')
        #with shared_arr.get_lock():  # synchronize access
            arr = np.frombuffer(shared_arr.get_obj(),dtype=np.float32)  # no data copying
            arr[:] = np.random.randn(1000).astype(np.float32)*100
            event.set()


def tonumpyarray(mp_arr):
    return np.frombuffer(mp_arr.get_obj(), dtype=np.float32)

def update_plot(plot_instance):
    if event.is_set():
        plot_instance["line1"].data[:, 1] = arr
        event.clear()

if __name__ == "__main__":
    N = 1000
    y0 = np.random.uniform(size=N).astype(np.float32)
    shared_arr = mp.Array(ctypes.c_float, y0)
    event = mp.Event()  # added event to avoid refreshing plot when there is no new data
    event.set()
    arr = tonumpyarray(shared_arr)

    # fill with random values
    xs = np.linspace(0, N-1, N, dtype=np.float32)
    data = np.dstack((xs, arr))[0]
    plot_l = Plot()
    line_graphic = plot_l.add_line(data=data, thickness=5, colors="magenta", name="line1")
    plot_l.show()
    plot_l.add_animations(update_plot)
    p = mp.Process(target=generate_ydata, args=(shared_arr,event))
    p.start()
    run_plot()

**Comment by kushalkolar** [comment]
glad you figured it out, open a new issue if you have further question :D
