### ISSUE TITLE
scatter notebook

### ISSUE THREAD

**Issue by vkonan** [kushalkolar/fastplotlib#208]
Found an error in the scatter notebook https://github.com/kushalkolar/fastplotlib/blob/6712c41293107f80cdcd32eb080802df1261770d/examples/scatter.ipynb#L67-L69

![Screen Shot 2023-05-24 at 2 55 35 PM](https://github.com/kushalkolar/fastplotlib/assets/101821671/1f83c4b6-6af3-4410-8ca5-9d507bfe01dd)

`AttributeError: 'list' object has no attribute 'shape'`

**Comment by kushalkolar** [comment]
you might be on an old version of `fastplotlib`, `pip install -U fastplotlib`

**Comment by vkonan** [comment]
My version is current (v0.1.0a9). I also redownloaded the repo. Still got the error.

**Comment by kushalkolar** [comment]
just ignore the cameras argument, you're only working on 2d plots right?

**Comment by kushalkolar** [comment]
There is a simpler scatter example at the end of the `simple.ipynb` notebook

**Comment by kushalkolar** [comment]
I just tested this:

```python
contours_good, coms = df.iloc[INDEX].cnmf.get_contours("good", swap_dim=False)

plot = fpl.Plot()

for contour in contours_good:
    plot.add_scatter(contour, sizes=2)

plot.show()
```

![image](https://github.com/kushalkolar/fastplotlib/assets/9403332/a372fc51-59da-4ce8-add9-c50edef09df6)

**Comment by vkonan** [comment]
this is super helpful. I'll test it out and report back on that thread. Thank you!

**Comment by kushalkolar** [comment]
closing, feel free to open if you still have issues.
