### ISSUE TITLE
should really just make `ImageWidget` use `GridPlot` even when using just 1 data array

### ISSUE THREAD

**Issue by kushalkolar** [kushalkolar/fastplotlib#222]
gets rid of conditionals and repetitive code

@clewis7 thoughts?

**Comment by clewis7** [comment]
I thought the same thing, would be a simple refactor I think and would handle the issues I was having in `set_data()`

**Comment by clewis7** [comment]
can assign to me if you want

**Comment by kushalkolar** [comment]
good luck with this :spaghetti:

**Comment by kushalkolar** [comment]
done in #230
