### ISSUE TITLE
dynamically add plot after plot already rendered 

### ISSUE THREAD

**Issue by clewis7** [kushalkolar/fastplotlib#223]
had a thought in the shower....

what if we made it possible to do something like:
`plot.add_plot(position="right")`

and that would change the plot to a gridplot with shape (1,2) with the left plot having the original graphics and the right plot being empty to start

I thought it might be useful in the event that you create a plot and have done some manipulations to the graphics and decide you need another plot, @kushalkolar thoughts?

**Comment by kushalkolar** [comment]
mostly a duplicate of #181, closing to reduce clutter
