### ISSUE TITLE
running CI only when not a draft

### ISSUE THREAD

**Issue by clewis7** [kushalkolar/fastplotlib#232]
want to make sure that CI does not run until PR is complete so that we do not waste action minutes 
- need to investigate if CI runs for drafts
- how to automatically make a PR a draft when first created

**Comment by kushalkolar** [comment]
> how to automatically make a PR a draft when first created 

![image](https://github.com/kushalkolar/fastplotlib/assets/9403332/94576fdf-51f2-4cbc-9fca-1231dd2e47a6)

**Comment by kushalkolar** [comment]
We really need this, it's been only 3 days and it's just 1.6 MB of pngs lol :joy: 

![image](https://github.com/kushalkolar/fastplotlib/assets/9403332/d014607e-abe3-425b-a4ee-c4487e71fe26)

**Comment by kushalkolar** [comment]
@clewis7 try this? https://github.com/reviewdog/action-eslint/issues/29#issuecomment-985939887

**Comment by clewis7** [comment]
I think that looks good, it will at least not run if a PR is a draft but I'm still not sure there is a way to force PRs to initially be drafts...I think it is pretty user-controlled
