### ISSUE TITLE
indexing selectors by name

### ISSUE THREAD

**Issue by clewis7** [kushalkolar/fastplotlib#246]
currently can only index plot graphics by name, for example:

```
import fastplotlib as fpl
import numpy as np

data = np.random.rand(512, 512)
plot  = fpl.Plot()
plot.add_image(data=data, name='image')

plot['image']
```

however, if you have named selectors, you cannot index them in the same manor

I think this would be a nice feature to have, would help me with my behavior stuff

@kushalkolar thoughts?

**Comment by kushalkolar** [comment]
When adding a selector does it check to make sure the name is unique
amongst both graphics and selectors?

You can just add this functionality to the current __getitem__.

**Comment by clewis7** [comment]
should be a simple fix
