### ISSUE TITLE
Colormaps not found (Windows install)

### ISSUE THREAD

**Issue by EricThomson** [kushalkolar/fastplotlib#37]
After installing on Windows using:

    pip install git+https://github.com/kushalkolar/fastplotlib.git

When I try to create simple plots:

```
plot = Plot()

data = np.random.rand(512, 512) * 255
plot.image(data=data,  vmin=0, vmax=255, cmap='viridis')

```

I get the following:

`FileNotFoundError: C:\Users\Eric\miniconda3\envs\ds\lib\site-packages\fastplotlib\colormaps\viridis not found.
`

It turns out the install isn't generating the `colormaps` directory, so my workaround is to create such a directory in the local repo, and copy/paste all the colormap files in from fastplotlib into that directory (using [download directory](https://download-directory.github.io/). It's a puzzle why the pip installer isn't working correctly. 

I've seen this on both of my Windows computers, and when I install on my Ubuntu machine things work fine.

**Comment by EricThomson** [comment]
Tried with this update, and it did generate the `colormaps` directory, but not the files in the directory.

**Comment by kushalkolar** [comment]
I tried adding an `__init__.py` to the colormaps dir, if you install from github now does it get the cmaps dir?

**Comment by kushalkolar** [comment]
This seems to work well now, haven't heard of issues and it was the easiest thing to install at the January workshop.
