### ISSUE TITLE
remove `simplejpeg` as hard dependency

### ISSUE THREAD

**Issue by kushalkolar** [kushalkolar/fastplotlib#54]
on windows the wheel for `simplejpeg` must be built and there seems to be no precompiled package available for it

**Comment by almarklein** [comment]
> It seems like there are? https://pypi.org/project/simplejpeg/#files

**Comment by kushalkolar** [comment]
I think it needs some C extensions to be built during installation, I tried
to install it on a windows computer recently and it told me to install the
Microsoft build tools. Will check more closely.

**Comment by kushalkolar** [comment]
done in https://github.com/kushalkolar/fastplotlib/commit/61d2903359895fa5b22ee64992a4b11668d9dccd
