### ISSUE TITLE
Line handling of nans

### ISSUE THREAD

**Issue by EricThomson** [kushalkolar/fastplotlib#67]
When data contains nans rendering doesn't work for line objects. Images work (i.e., the nans just show up as zeros). 

```
xs = np.linspace(0, 30, 500)
ys = np.sin(xs)
ys[30:50] = np.nan
data1 = np.dstack([xs, ys])[0]

plot_l = Plot()
plot_l.line(data=data1, size=2, cmap="jet")
plot_l.show()
```
Compare to following which shows up fine (line renders except the nans which are just blank -- obviously could be handled differently this is just one option):
```
import matplotlib.pyplot as plt
plt.plot(xs, ys)
```

In practice this comes up frequently as the caiman coordinates have nans in them fairly often (right now I just filter out those nan-containing rows).

**Comment by kushalkolar** [comment]
Yes I see, I encountered this issue with the HistogramGraphic previously and fixed it in #28 

We could just implement it in the base `Graphic` when data are converted to `float32`, do you want to do your first PR? :D https://github.com/kushalkolar/fastplotlib/blob/master/fastplotlib/graphics/_base.py#L19

**Comment by EricThomson** [comment]
Seems like a good one for start with for sure :) Might take me a little while to get to it (weekend likely).

**Comment by kushalkolar** [comment]
thinking about this more, for lines we don't want to show it as zeros though becuase this will actually move the position of the line vertex, maybe we can set the alpha value for the color at those points to zero

**Comment by EricThomson** [comment]
Yes the zero strategy won’t work for lines. Either need to interpolate or make the relevant bits disappear. For the latter, could split into multiple lines or the alpha trick sound good. Having to track multiple separate line objects would probably be a pain!

**Comment by kushalkolar** [comment]
splitting into multiple lines would be a major pain, definitely try the alpha method!

**Comment by kushalkolar** [comment]
I made a PR in `pygfx` which should fix this, it was a camera issue because autoscaling isn't possible when the bbox is nan:

https://github.com/pygfx/pygfx/pull/540

**Comment by kushalkolar** [comment]
fixed in https://github.com/pygfx/pygfx/pull/540
